todos/Tun-master/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('reminder.urls')),
    path("", include('users.urls')),

]

todos/Tun-master/reminder/urls.py
from django.urls import path
from reminder import views

app_name = 'reminder'
urlpatterns = [
    # urls for template
    path('', views.ReminderList.as_view(), name='tasks'),
    path('task/add/', views.ReminderCreate.as_view(), name='task_add'),
    path('task-update/<int:pk>/',
         views.ReminderUpdate.as_view(), name='task_update'),
    path('task/assign/', views.ReminderAssign.as_view(), name='task_assign'),
    path('task/<int:pk>/delete/',
         views.ReminderDelete.as_view(), name='task_delete'),
    path('task/<int:pk>/finish/',
         views.finish_task, name='finish_task'),
    # urls for API
    path('api/', views.ReminderListAPI.as_view()),
    path('api/<int:pk>/', views.ReminderDetailAPI.as_view()),
    path('api/add/', views.ReminderCreateAPI.as_view()),
    path('api/<int:pk>/finish/', views.finish_task_API),
]

todos/Tun-master/users/urls.py
from django.urls import path
from users import views
from rest_framework.authtoken import views as auth_token_views

urlpatterns = [
    # template urls
    path('register/', views.register, name='register'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    # api urls
    path("api/register/", views.RegisterView.as_view()),
    path('api/token/', auth_token_views.obtain_auth_token),
]

todos/Tun-master/reminder/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from twilio.rest import Client

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    is_finished = models.BooleanField(default=False)
    is_notified = models.BooleanField(default=False)
    is_assigned = models.BooleanField(default=False)
    assigned_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='item_assigned')
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='item_created')

    class Meta:
        ordering = ('due_date',)

    def __str__(self):
        return self.title

    def has_alarm(self):
        return self.due_date is not None

    def has_expired(self):
        if self.has_alarm():
            return timezone.now() > self.due_date
        else:
            return False

    def status(self):
        if self.is_finished:
            return 'Finished'
        elif self.has_expired():
            return 'Expired'
        else:
            return 'In progress'

    def save(self, *args, **kwargs):
        if self.is_assigned:
            # Use placeholders instead of real keys and numbers
            account_sid = 'YOUR_TWILIO_ACCOUNT_SID_HERE'
            auth_token = 'YOUR_TWILIO_AUTH_TOKEN_HERE'
            client = Client(account_sid, auth_token)

            message = client.messages.create(
                body=f"{self.title} has been assigned by {self.assigned_by} due {self.due_date}",
                from_='+YOUR_TWILIO_PHONE_NUMBER',
                to='+RECIPIENT_PHONE_NUMBER'
            )

            print(message.sid)
        return super().save(*args, **kwargs)

todos/Tun-master/reminder/forms.py
from django import forms
from django.forms import ModelForm
from .models import Task
from django.forms import widgets


class ReminderCreateForm(ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date']
        widgets = {
            'due_date': widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class ReminderAssignForm(ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'owner']
        widgets = {
            'due_date': widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class ReminderUpdateForm(ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description',
                  'due_date', 'is_finished', 'is_notified']
        widgets = {
            'due_date': widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

todos/Tun-master/reminder/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django.db.models import F
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.response import Response

from reminder.models import Task
from reminder.forms import ReminderCreateForm, ReminderUpdateForm, ReminderAssignForm
from reminder import serializers

User = get_user_model()


# Views for template
class ReminderList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'all_tasks'
    template_name = 'reminder/task_list.html'

    def get_queryset(self):
        return Task.objects.filter(owner=self.request.user).order_by(F('due_date').asc(nulls_last=True))


class ReminderCreate(LoginRequiredMixin, CreateView):
    model = Task
    form_class = ReminderCreateForm
    template_name = 'reminder/task_add.html'
    success_url = reverse_lazy('reminder:tasks')

    def form_valid(self, form):
        # the authenticated user will be set as the owner of the task
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ReminderAssign(LoginRequiredMixin, CreateView):
    model = Task
    form_class = ReminderAssignForm
    template_name = 'reminder/task_assign.html'
    success_url = reverse_lazy('reminder:tasks')

    def form_valid(self, form):
        # authenticated user will be set as the person who assigned the task
        form.instance.is_assigned = True
        form.instance.assigned_by = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # available owners to assign a task. all users are available expect for the person who is assigning
        context = super().get_context_data(**kwargs)
        context['form'].fields['owner'].queryset = User.objects.exclude(
            username=self.request.user)
        return context


class ReminderUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = ReminderUpdateForm
    template_name = 'reminder/task_update.html'
    success_url = reverse_lazy('reminder:tasks')


class ReminderDelete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('reminder:tasks')


def finish_task(request, pk):
    task = Task.objects.get(id=pk)
    task.is_finished = True
    task.save()

    return redirect('reminder:tasks')


# views for API
class ReminderCreateAPI(generics.CreateAPIView):
    serializer_class = serializers.ReminderCreateSerializer

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class ReminderAssignAPI(generics.CreateAPIView):
    serializer_class = serializers.ReminderAssignSerializer

    def perform_create(self, serializer):
        serializer.save(is_assigned=True)
        serializer.save(assigned_by=self.request.user)


class ReminderListAPI(generics.ListAPIView):
    serializer_class = serializers.ReminderListSerializer

    def get_queryset(self):
        return Task.objects.filter(owner=self.request.user).order_by(F('due_date').asc(nulls_last=True))


class ReminderDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = serializers.ReminderDetailSerializer


@api_view(['GET'])
def finish_task_API(request, pk):

    task = Task.objects.get(id=pk)
    task.is_finished = True
    task.save()

    context = {
        'code': 'task_finished'
    }
    return Response(context)

todos/Tun-master/reminder/templates/reminder/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}{% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
    <style>
      {% block style %}{% endblock style %}k
    </style>
  <body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-9">
              <div class="card rounded-3">
                <div class="card-body p-4">
                  <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item ">
                          <a class="nav-link {% block tasks_active %}{% endblock tasks_active %}" href="{% url 'reminder:tasks' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" fill="currentColor" class="bi bi-card-checklist" viewBox="0 0 16 16">
                              <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                              <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"/>
                            </svg>
                            Tasks
                          </a>
                        </li>
                      </ul>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link {% block add_task_active %}{% endblock add_task_active %}" href="{% url 'reminder:task_add' %}">
                              <svg xmlns="http://www.w3.org/2000/svg" width="22" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
                                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                              </svg>
                              Add task
                            </a>
                          </li>

                          <li class="nav-item">
                            <a class="nav-link {% block assign_task_active %}{% endblock assign_task_active %}" href="{% url 'reminder:task_assign' %}">
                              <svg xmlns="http://www.w3.org/2000/svg" width="25"  fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
                                <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
                              </svg>
                              Assign Task
                            </a>
                          </li>
                          

                        </ul>
                        <ul class="navbar-nav">

                          <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                              </svg>
                              {{user.first_name}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                              
                            </ul>
                          </li>
                        </ul>
                        
                      </div>
                    </div>
                  </nav>
                    {% block body %}

                    {% endblock body %}

                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

todos/Tun-master/reminder/templates/reminder/task_add.html
<!DOCTYPE html>
{% extends 'reminder/base.html' %}
{% block title %} add task {% endblock title %}

{% block add_task_active %}active{% endblock add_task_active %}
{% block body %}
{% load crispy_forms_tags %}
 <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Add</button>
    </form>
{% endblock body %}

todos/Tun-master/reminder/templates/reminder/task_assign.html
<!DOCTYPE html>
{% extends 'reminder/base.html' %}
{% block title %}Task Assign{% endblock title %}

{% block assign_task_active %}active{% endblock assign_task_active %}
{% block body %}
{% load crispy_forms_tags %}
 <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Assign</button>
    </form>
{% endblock body %}

todos/Tun-master/reminder/templates/reminder/task_form.html
{% extends 'reminder/base.html' %}
{% block title %} updating reminder {% endblock title %}

{% block body %}
{% load crispy_forms_tags %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Update</button>
    </form>
{% endblock body %}

todos/Tun-master/reminder/templates/reminder/task_list.html
{% extends 'reminder/base.html' %} 
{% block title %} reminder {% endblock title%} 
{% block style %} 
.inside{ 
  height:50vh; 
  overflow-y: 
  scroll; 
} 
.passed{
color:#86242A 
} 
td{ max-width:5rem; } 
{% endblock style %} 
{% block tasks_active%} active {% endblock tasks_active %} 
{% block body %}

<h4 class="text-center my-3 pb-3">To Do App</h4>

<div class="inside">
  <table class="table mb-4">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Todo item</th>
        <th scope="col">Status</th>
        <th scope="col">due date</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    {% if all_tasks%} 
      {% for task in all_tasks %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>

        <td>
          {% if task.is_finished %}
          <del>
            <a href="{% url 'reminder:task_update' task.id %}">
              {{task.title}}</a
            >
          </del>
          {% elif task.is_assigned%}
          <a href="{% url 'reminder:task_update' task.id %}">
            {{task.title}}
            <p>assigned by {{task.assigned_by.first_name}}</p></a
          >

          {% else %}
          <a href="{% url 'reminder:task_update' task.id %}"> {{task.title}}</a>

          {% endif %}
        </td>

        {% if task.status == "Expired" %}
        <td class="passed">{{task.status}}</td>
        {% else %}
        <td>{{task.status}}</td>

        {% endif %} 
        {% if task.has_alarm %}
        <td>{{task.due_date}}</td>
        {% else %}
        <td>No due date</td>
        {% endif %}
        <td>
          <form
            action="{% url 'reminder:task_delete' task.id%}"
            method="post"
            style="display: inline"
          >
            {% csrf_token %}
            <button
              type="submit"
              class="btn"
              onclick="return confirm('are you sure?')"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                fill="#D31A38"
                class="bi bi-trash-fill"
                viewBox="0 0 16 16"
              >
                <path
                  d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"
                />
              </svg>
            </button>
          </form>
          {% if task.has_alarm %}
          <a
            href="{% url 'reminder:finish_task' task.id %}"
            class="btn"
            onclick="return confirm('you have set an alarm for this task.\nBy setting this task as a is_finished one you will not be is_notified for it.')"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="green"
              class="bi bi-check-square"
              viewBox="0 0 16 16"
            >
              <path
                d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"
              />
              <path
                d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"
              />
            </svg>
          </a>
          {% else %}
          <a href="{% url 'reminder:finish_task' task.id %}" class="btn">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="green"
              class="bi bi-check-square"
              viewBox="0 0 16 16"
            >
              <path
                d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"
              />
              <path
                d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"
              />
            </svg>
          </a>
          {% endif %}
        </td>
      </tr>
    </tbody>
    {% endfor %} {% endif %}
  </table>
</div>
{% endblock body %}

todos/Tun-master/reminder/templates/reminder/task_update.html
<!DOCTYPE html>
{% extends 'reminder/base.html' %}
{% block title %} update task {% endblock title %}

{% block body %}
{% load crispy_forms_tags %}
 <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Update</button>
    </form>
{% endblock body %}